services:
  - type: web
    name: loveny
    runtime: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn loveny_site.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
