from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('app/', views.swipe_view, name='swipe_card'), 
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('password-reset/', views.SafePasswordResetView.as_view(), name='password_reset_alias'),
    path('create-profile/', views.create_profile, name='create_profile'),
    path('profile/', views.profile_detail, name='profile'),
    path('profile/me/', views.profile_detail, name='profile_me'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('account/delete/', views.delete_account, name='delete_account'),
    
    path('settings/', views.settings_view, name='settings'),
    path('api/settings/switch-mode/', views.switch_profile_mode_api, name='switch_profile_mode_api'),
    path('settings/blocked/', views.blocked_users_view, name='blocked_users'),

    path('api/conversations/', views.conversations_api, name='conversations_api'),
    path('api/conversations/<int:conversation_id>/messages/', views.conversation_messages_api, name='conversation_messages_api'),
    path('api/conversations/<int:conversation_id>/send/', views.conversation_send_api, name='conversation_send_api'),
    path('api/chat/send-gift/', views.chat_send_gift_api, name='chat_send_gift_api'),
    path('api/chat/stickers/', views.chat_stickers_api, name='chat_stickers_api'),
    path('conversations/<int:conversation_id>/', views.conversation_room, name='conversation_room'),
    path('api/subscription-plans/', views.subscription_plans_api, name='subscription_plans_api'),
    path('api/calls/initiate/', views.call_initiate_api, name='call_initiate_api'),
    path('api/calls/incoming/', views.incoming_calls_api, name='incoming_calls_api'),
    path('api/calls/<uuid:room_id>/respond/', views.call_respond_api, name='call_respond_api'),
    path('api/calls/<uuid:room_id>/end/', views.call_end_api, name='call_end_api'),
    path('api/calls/<uuid:room_id>/heartbeat/', views.call_heartbeat_api, name='call_heartbeat_api'),
    path('api/calls/<uuid:room_id>/gift/', views.call_gift_api, name='call_gift_api'),
    path('api/calls/<uuid:room_id>/', views.call_status_api, name='call_status_api'),
    path('api/calls/<uuid:room_id>/signals/', views.call_signals_api, name='call_signals_api'),
    path('api/calls/<uuid:room_id>/signals/send/', views.call_signal_send_api, name='call_signal_send_api'),
    path('sex-call/', views.sex_call_hub, name='sex_call_hub'),
    path('call/<uuid:room_id>/', views.call_room_page, name='call_room_page'),
    path('api/sex-call/hosts/', views.sex_call_hosts_api, name='sex_call_hosts_api'),
    path('api/wallet/convert-diamonds/', views.convert_diamonds_api, name='convert_diamonds_api'),
    path('api/wallet/balance/', views.wallet_balance_api, name='wallet_balance_api'),
    path('api/wallet/claim-welcome/', views.claim_welcome_bonus_api, name='claim_welcome_bonus_api'),
    path('api/wallet/check-in/', views.daily_checkin_api, name='daily_checkin_api'),
    path('api/wallet/withdraw/', views.withdrawal_request_api, name='withdrawal_request_api'),
    path('api/wallet/history/', views.wallet_history_api, name='wallet_history_api'),
    path('api/coins/packages/', views.coin_packages_api, name='coin_packages_api'),
    path('api/gifts/', views.gifts_api, name='gifts_api'),
    path('api/config/', views.site_config_api, name='site_config_api'),
    path('api/hosts/online/', views.online_hosts_api, name='online_hosts_api'),
    path('api/calls/quick-match/', views.quick_call_match_api, name='quick_call_match_api'),
    path('api/get_profiles/', views.get_profiles_json, name='get_profiles_json'),
    path('action/', views.swipe_action, name='swipe_action'),
    path('matches/', views.match_list, name='match_list'),
    path('messages/', views.messages_inbox, name='messages_inbox'),
    path('chats/', views.messages_inbox, name='chats'),
    path('matches/<int:match_id>/chat/', views.chat_room, name='chat_room'),
    path('likes/', views.likes_list, name='likes_list'),
    path('privacy-policy/', views.privacy, name='privacy'),
    path('terms-of-service/', views.terms, name='terms'),
    
    path('users/<int:pk>/', views.public_profile, name='public_profile'),
    path('api/connect/<int:user_id>/', views.quick_connect_api, name='quick_connect_api'),
    path('api/say-hi/<int:user_id>/', views.quick_say_hi_api, name='quick_say_hi_api'),

    path('premium/', views.premium_landing, name='premium_landing'),
    path('premium/checkout/', views.premium_checkout, name='premium_checkout'),
    path('coins/shop/', views.premium_checkout, {'mode': 'COINS'}, name='coin_shop'),
    path('premium/success/', views.premium_success, name='premium_success'),
    path('premium/verify/', views.verify_payment, name='verify_payment'),
    path('contact/', views.contact, name='contact'),
    path('swipe/rewind/', views.rewind_last_swipe, name='rewind_swipe'),

    # Hookup Mode & Dual-Fiat Paystack Handshake URLs
    path('hookup/', views.hookup_discovery_view, name='hookup_discovery'),
    path('hookup/chat/<uuid:match_id>/', views.hookup_chat_room_view, name='hookup_chat_room'),
    path('api/hookup/request/', views.hookup_request_api, name='hookup_request_api'),
    path('api/hookup/<uuid:match_id>/respond/', views.hookup_respond_api, name='hookup_respond_api'),
    path('api/hookup/<uuid:match_id>/pay/', views.hookup_initialize_payment_api, name='hookup_initialize_payment_api'),
    path('api/hookup/<uuid:match_id>/verify/', views.hookup_verify_payment_api, name='hookup_verify_payment_api'),
    path('api/hookup/chat/<uuid:match_id>/messages/', views.hookup_messages_api, name='hookup_messages_api'),
    path('api/hookup/chat/<uuid:match_id>/send/', views.hookup_send_message_api, name='hookup_send_message_api'),
    path('api/notifications/global/', views.global_notifications_api, name='global_notifications_api'),
    path('api/report/', views.report_user_api, name='report_user_api'),
    path('payments/paystack/webhook/', views.paystack_webhook_api, name='paystack_webhook'),
]