# Generated by Django 5.2.3 on 2025-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilephoto',
            options={'ordering': ['uploaded_at'], 'verbose_name_plural': 'Profile Media'},
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=models.FileField(upload_to='profile_media/'),
        ),
    ]
