# Generated by Django 5.2.8 on 2025-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_alter_profilephoto_options_alter_profilephoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_age_pref',
            field=models.IntegerField(default=50, help_text='Maximum age of people you want to see.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_age_pref',
            field=models.IntegerField(default=18, help_text='Minimum age of people you want to see.'),
        ),
    ]
