# Generated by Django 5.2.8 on 2025-11-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0003_profile_max_age_pref_profile_min_age_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
