# Generated by Django 5.2.8 on 2025-11-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_profile_job_title_profile_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Dating Profile', 'verbose_name_plural': 'Dating Profiles'},
        ),
    ]
