# Generated by Django 6.0.1 on 2026-01-24 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0006_profile_premium_expiry_profile_premium_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_age_pref',
            field=models.IntegerField(default=18, help_text='Minimum age of people you want to see.', validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
