# Generated by Django 6.0.1 on 2026-09-27 21:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0007_alter_profile_age_alter_profile_min_age_pref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='has_direct_interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SUGAR', 'Sugar relationship')], default='DATING', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_distance_km',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SUGAR', 'Sugar relationship')], default='DATING', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_in_discovery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sugar_allowance',
            field=models.CharField(blank=True, help_text='Optional allowance expectations. Do not include payment details.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='sugar_arrangement',
            field=models.CharField(blank=True, choices=[('LONG_TERM', 'Long-term arrangement'), ('CASUAL', 'Casual arrangement'), ('TRAVEL', 'Travel and experiences'), ('MENTORSHIP', 'Mentorship and lifestyle')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sugar_lifestyle',
            field=models.CharField(blank=True, help_text='Lifestyle preferences for a sugar arrangement.', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='sugar_role',
            field=models.CharField(blank=True, choices=[('DADDY', 'Sugar Daddy'), ('MUMMY', 'Sugar Mummy'), ('BABY', 'Sugar Baby')], max_length=10),
        ),
        migrations.AddField(
            model_name='swipe',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swipe',
            name='mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SUGAR', 'Sugar relationship')], default='DATING', max_length=10),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20)),
                ('plan_type', models.CharField(max_length=20)),
                ('amount_kobo', models.PositiveIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=2000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dating.match')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at', 'id'],
                'indexes': [models.Index(fields=['match', 'sent_at'], name='dating_chat_match_i_af84b9_idx')],
            },
        ),
    ]
