# Generated by Django 6.0.1 on 2026-09-27 21:42

from django.db import migrations, models


def move_legacy_entitlements(apps, schema_editor):
    Profile = apps.get_model('dating', 'Profile')
    PaymentTransaction = apps.get_model('dating', 'PaymentTransaction')

    for profile in Profile.objects.exclude(premium_expiry=None).iterator():
        if profile.relationship_mode == 'DATING':
            profile.dating_premium_tier = profile.premium_tier or ''
            profile.dating_premium_expiry = profile.premium_expiry
            profile.save(update_fields=['dating_premium_tier', 'dating_premium_expiry'])
        else:
            profile.hookup_sugar_premium_tier = profile.premium_tier or ''
            profile.hookup_sugar_premium_expiry = profile.premium_expiry
            profile.save(update_fields=[
                'hookup_sugar_premium_tier',
                'hookup_sugar_premium_expiry',
            ])

    modes = dict(Profile.objects.values_list('user_id', 'relationship_mode'))
    for payment in PaymentTransaction.objects.all().iterator():
        payment.product = (
            'DATING'
            if modes.get(payment.user_id, 'DATING') == 'DATING'
            else 'HOOKUP_SUGAR'
        )
        payment.save(update_fields=['product'])


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0008_match_has_direct_interest_match_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='product',
            field=models.CharField(choices=[('DATING', 'Dating Premium'), ('HOOKUP_SUGAR', 'Hookup and Sugar VIP')], default='DATING', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='dating_premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dating_premium_tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='hookup_sugar_premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hookup_sugar_premium_tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(move_legacy_entitlements, migrations.RunPython.noop),
    ]
