# Generated by Django 6.0.1 on 2026-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0009_paymenttransaction_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hookup_sugar_premium_expiry',
            new_name='hookup_sexcall_premium_expiry',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='hookup_sugar_premium_tier',
            new_name='hookup_sexcall_premium_tier',
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SUGAR', 'Sugar relationship'), ('SEX_CALL', 'Sex Call')], default='DATING', max_length=12),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='product',
            field=models.CharField(choices=[('DATING', 'Dating Premium'), ('HOOKUP_SUGAR', 'Hookup, Sex Call and Sugar VIP')], default='DATING', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SUGAR', 'Sugar relationship'), ('SEX_CALL', 'Sex Call')], default='DATING', max_length=12),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SUGAR', 'Sugar relationship'), ('SEX_CALL', 'Sex Call')], default='DATING', max_length=12),
        ),
    ]
