# Generated by Django 6.0.1 on 2026-09-27 22:42

from django.db import migrations, models


def normalize_legacy_modes_and_products(apps, schema_editor):
    Profile = apps.get_model('dating', 'Profile')
    Swipe = apps.get_model('dating', 'Swipe')
    Match = apps.get_model('dating', 'Match')
    PaymentTransaction = apps.get_model('dating', 'PaymentTransaction')

    Profile.objects.filter(relationship_mode='SUGAR').update(relationship_mode='HOOKUP')
    Swipe.objects.filter(mode='SUGAR').update(mode='HOOKUP')
    Match.objects.filter(mode='SUGAR').update(mode='HOOKUP')
    PaymentTransaction.objects.filter(product='HOOKUP_SUGAR').update(
        product='HOOKUP_SEX_CALL',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0010_rename_hookup_sugar_premium_expiry_profile_hookup_sexcall_premium_expiry_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_modes_and_products, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='profile',
            name='sugar_allowance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sugar_arrangement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sugar_lifestyle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sugar_role',
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SEX_CALL', 'Sex Call')], default='DATING', max_length=12),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='product',
            field=models.CharField(choices=[('DATING', 'Dating Premium'), ('HOOKUP_SEX_CALL', 'Hookup and Sex Call Premium')], default='DATING', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SEX_CALL', 'Sex Call')], default='DATING', max_length=12),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SEX_CALL', 'Sex Call')], default='DATING', max_length=12),
        ),
    ]
