# Generated by Django 6.0.1 on 2026-10-03 13:30

import django.core.validators
import django.db.models.deletion
import django.db.models
from django.db import migrations, models


def migrate_subscription_data(apps, schema_editor):
    Profile = apps.get_model('dating', 'Profile')
    SubscriptionPlan = apps.get_model('dating', 'SubscriptionPlan')
    PaymentTransaction = apps.get_model('dating', 'PaymentTransaction')

    Profile.objects.update(
        hookup_premium_expiry=django.db.models.F('hookup_sexcall_premium_expiry'),
        hookup_premium_tier=django.db.models.F('hookup_sexcall_premium_tier'),
        sex_call_premium_expiry=django.db.models.F('hookup_sexcall_premium_expiry'),
        sex_call_premium_tier=django.db.models.F('hookup_sexcall_premium_tier'),
    )

    initial_plans = (
        ('DATING', 'Silver', 3, '200.00', False),
        ('DATING', 'Gold', 7, '1000.00', True),
        ('DATING', 'Platinum', 30, '3500.00', False),
        ('HOOKUP', 'Silver', 3, '300.00', False),
        ('HOOKUP', 'Gold', 7, '700.00', True),
        ('HOOKUP', 'Platinum', 30, '1500.00', False),
        ('SEX_CALL', 'Silver', 3, '300.00', False),
        ('SEX_CALL', 'Gold', 7, '700.00', True),
        ('SEX_CALL', 'Platinum', 30, '1500.00', False),
    )
    for category, tier_name, duration_days, price, is_popular in initial_plans:
        SubscriptionPlan.objects.get_or_create(
            category=category,
            duration_days=duration_days,
            defaults={
                'tier_name': tier_name,
                'price': price,
                'is_popular': is_popular,
                'features': [
                    'Unlimited likes',
                    'See who liked you',
                    f'{duration_days} days of {category.replace("_", " ").title()} access',
                ],
                'is_active': True,
            },
        )

    PaymentTransaction.objects.filter(product='HOOKUP_SEX_CALL').update(product='HOOKUP')


def reverse_subscription_data(apps, schema_editor):
    Profile = apps.get_model('dating', 'Profile')
    PaymentTransaction = apps.get_model('dating', 'PaymentTransaction')

    for profile in Profile.objects.all().iterator():
        hookup_expiry = profile.hookup_premium_expiry
        sex_call_expiry = profile.sex_call_premium_expiry
        if sex_call_expiry and (not hookup_expiry or sex_call_expiry > hookup_expiry):
            expiry = sex_call_expiry
            tier = profile.sex_call_premium_tier
        else:
            expiry = hookup_expiry
            tier = profile.hookup_premium_tier
        profile.hookup_sexcall_premium_expiry = expiry
        profile.hookup_sexcall_premium_tier = tier
        profile.save(update_fields=[
            'hookup_sexcall_premium_expiry',
            'hookup_sexcall_premium_tier',
        ])

    PaymentTransaction.objects.filter(product='HOOKUP').update(product='HOOKUP_SEX_CALL')


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0012_seed_general_interest_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hookup_premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hookup_premium_tier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex_call_premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex_call_premium_tier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='product',
            field=models.CharField(choices=[('DATING', 'Dating Premium'), ('HOOKUP', 'Hookup Premium'), ('SEX_CALL', 'Sex Call Premium')], default='DATING', max_length=12),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SEX_CALL', 'Sex Call')], max_length=12)),
                ('tier_name', models.CharField(max_length=50)),
                ('duration_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Nigerian naira (₦).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_popular', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', 'duration_days'),
                'constraints': [models.UniqueConstraint(fields=('category', 'duration_days'), name='unique_subscription_plan_category_duration'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='subscription_plan_price_positive')],
            },
        ),
        migrations.RunPython(migrate_subscription_data, reverse_subscription_data),
        migrations.RemoveField(
            model_name='profile',
            name='hookup_sexcall_premium_expiry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hookup_sexcall_premium_tier',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='dating.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan_type',
            field=models.CharField(max_length=50),
        ),
    ]
