# Generated by Django 6.0.1 on 2026-10-04 21:22

from django.conf import settings
from django.db import migrations, models


def isolate_existing_test_profiles(apps, schema_editor):
    Profile = apps.get_model('dating', 'Profile')
    user_app, user_model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app, user_model)
    database = schema_editor.connection.alias
    test_users = User.objects.using(database).filter(
        username__startswith='test_profile_',
    )
    Profile.objects.using(database).filter(user__in=test_users).update(
        is_test_profile=True,
        is_verified=False,
    )
    test_users.update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0015_callsession_callsignal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(
                blank=True,
                help_text='Private legacy contact field; not shown or used for external contact.',
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_test_profile',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(isolate_existing_test_profiles, migrations.RunPython.noop),
    ]
