# Generated by Django 6.0.1 on 2026-10-05 03:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0016_profile_is_test_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coins', models.PositiveIntegerField(help_text='Base coins')),
                ('bonus_coins', models.PositiveIntegerField(default=0, help_text='Extra free bonus coins')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Nigerian naira (₦).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_popular', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'price'),
            },
        ),
        migrations.AddField(
            model_name='callsession',
            name='coins_spent',
            field=models.PositiveIntegerField(default=0, help_text='Total coins deducted for this call'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Connected call duration in seconds'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='rate_per_minute',
            field=models.PositiveIntegerField(default=20, help_text='Coins per minute'),
        ),
        migrations.AddField(
            model_name='profile',
            name='coin_balance',
            field=models.PositiveIntegerField(default=0, help_text='Available coin balance for video calls & gifts'),
        ),
        migrations.AddField(
            model_name='profile',
            name='earned_diamonds',
            field=models.PositiveIntegerField(default=0, help_text='Diamonds earned by hosts from received calls & gifts'),
        ),
        migrations.AlterField(
            model_name='callsignal',
            name='signal_type',
            field=models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE candidate'), ('gift', 'In-call gift')], max_length=12),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='product',
            field=models.CharField(choices=[('DATING', 'Dating Premium'), ('HOOKUP', 'Hookup Premium'), ('SEX_CALL', 'Sex Call Premium'), ('COINS', 'Coin Pack')], default='DATING', max_length=12),
        ),
        migrations.CreateModel(
            name='CallGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type', models.CharField(choices=[('rose', 'Rose 🌹'), ('kiss', 'Kiss 💋'), ('champagne', 'Champagne 🥂'), ('crown', 'Crown 👑'), ('car', 'Supercar 🏎️')], max_length=20)),
                ('coins_cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='dating.callsession')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_call_gifts', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_call_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='coin_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='dating.coinpackage'),
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Coins (positive for credit, negative for debit) or Diamonds')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Coin Purchase'), ('WELCOME_BONUS', 'Welcome Bonus'), ('CALL_DEDUCTION', 'Call Minute Deduction'), ('CALL_EARNING', 'Host Call Diamond Earning'), ('CALL_REFUND', 'Call Refund / Grace Period'), ('GIFT_SENT', 'Gift Sent'), ('GIFT_RECEIVED', 'Gift Received')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='dating.callsession')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='dating.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='dating_coin_user_id_0b6399_idx')],
            },
        ),
    ]
