# Generated by Django 6.0.1 on 2026-10-05 06:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0018_seed_coin_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='Unique key (e.g. rose, kiss, champagne)', unique=True)),
                ('icon', models.CharField(default='🎁', help_text='Emoji symbol (e.g. 🌹, 💋, 🥂, 👑, 🏎️)', max_length=20)),
                ('coin_cost', models.PositiveIntegerField(default=10, help_text='Coin cost to send')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in gift drawer')),
            ],
            options={
                'ordering': ('order', 'coin_cost'),
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_rate_per_minute', models.PositiveIntegerField(default=20, help_text='Coins deducted per minute during Sex Calls')),
                ('grace_period_seconds', models.PositiveIntegerField(default=20, help_text='Calls ending under this duration are 100% free / 0 coins charged')),
                ('host_commission_percentage', models.PositiveIntegerField(default=70, help_text='Percentage of call coins and gifts awarded to hosts in diamonds (e.g. 70%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('welcome_bonus_coins', models.PositiveIntegerField(default=30, help_text='Free starter coins granted to new users')),
                ('min_diamond_withdrawal', models.PositiveIntegerField(default=500, help_text='Minimum diamond balance required for a host to request a cashout')),
                ('diamond_exchange_rate_naira', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Naira value per 1 diamond (e.g. ₦5.00/diamond => 500 diamonds = ₦2,500)', max_digits=8)),
                ('announcement_banner', models.CharField(blank=True, help_text="Top promotional banner text (e.g. '🔥 Weekend Special: 2x Host Diamonds!')", max_length=255)),
                ('is_announcement_active', models.BooleanField(default=False, help_text='Enable announcement banner across the app')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='is_host_ready',
            field=models.BooleanField(default=True, help_text='Ready to accept incoming video calls'),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_rate',
            field=models.PositiveSmallIntegerField(default=98, help_text='Host response rate %', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_calls_completed',
            field=models.PositiveIntegerField(default=0, help_text='Completed video calls count'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamonds_amount', models.PositiveIntegerField()),
                ('naira_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('PAID', 'Paid Out'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Payment transaction reference or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
