# Generated by Django 6.0.1 on 2026-10-05 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0021_chatmessage_message_type_chatmessage_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='diamond_exchange_rate_naira',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='min_diamond_withdrawal',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='diamond_to_coin_percentage',
            field=models.PositiveIntegerField(default=70, help_text='Coins received per 100 Diamonds exchanged (e.g. 70 means 100💎 = 70🪙). Closed loop - no real-money cashout.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='callsignal',
            name='signal_type',
            field=models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE candidate'), ('gift', 'In-call gift'), ('chat', 'Live In-Call Chat'), ('follow', 'Host Follow Event')], max_length=12),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Coin Purchase'), ('WELCOME_BONUS', 'Welcome Bonus'), ('CALL_DEDUCTION', 'Call Minute Deduction'), ('CALL_EARNING', 'Host Call Diamond Earning'), ('CALL_REFUND', 'Call Refund / Grace Period'), ('GIFT_SENT', 'Gift Sent'), ('GIFT_RECEIVED', 'Gift Received'), ('DIAMOND_CONVERSION', 'Diamond to Coin Exchange')], max_length=20),
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
