# Generated by Django 6.0.1 on 2026-10-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0023_update_coin_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_dnd',
            field=models.BooleanField(default=False, help_text='When enabled, incoming video call rings and notifications are silenced.'),
        ),
    ]
