# Generated by Django 6.0.1 on 2026-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0024_profile_is_dnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('connected', 'Connected'), ('active', 'Active'), ('ended', 'Ended'), ('declined', 'Declined'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=12),
        ),
    ]
