# Generated by Django 6.0.1 on 2026-10-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0025_callsession_connected_at_alter_callsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_checkin_date',
            field=models.DateField(blank=True, help_text='Last daily coin reward check-in date', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('gift', 'Gift'), ('sticker', 'Sticker'), ('image', 'Image')], db_index=True, default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Coin Purchase'), ('WELCOME_BONUS', 'Welcome Bonus'), ('CALL_DEDUCTION', 'Call Minute Deduction'), ('CALL_EARNING', 'Host Call Diamond Earning'), ('CALL_REFUND', 'Call Refund / Grace Period'), ('GIFT_SENT', 'Gift Sent'), ('GIFT_RECEIVED', 'Gift Received'), ('DIAMOND_CONVERSION', 'Diamond to Coin Exchange'), ('DAILY_CHECKIN', 'Daily Check-In Reward')], max_length=20),
        ),
    ]
