# Generated by Django 6.0.1 on 2026-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0026_profile_last_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checkin_streak',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive 7-day daily check-in streak (0 to 7)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_claimed_welcome',
            field=models.BooleanField(default=False, help_text='Whether newcomer joining gift has been claimed'),
        ),
    ]
