# Generated by Django 6.0.1 on 2026-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0027_profile_checkin_streak_profile_has_claimed_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='daily_checkin_coins',
            field=models.PositiveIntegerField(default=5, help_text='Coins awarded daily on Days 1 through 6 of the check-in streak'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='day_7_bonus_coins',
            field=models.PositiveIntegerField(default=10, help_text='Bonus coins awarded on Day 7 of the check-in streak (Grand Prize)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='day_7_bonus_diamonds',
            field=models.PositiveIntegerField(default=20, help_text='Diamonds awarded on Day 7 of the check-in streak (Grand Prize)'),
        ),
    ]
