# Generated by Django 6.0.1 on 2026-10-06 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0028_siteconfiguration_daily_checkin_coins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='off_platform_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Count of detected contact-info off-platform leak attempts'),
        ),
        migrations.AlterField(
            model_name='callsignal',
            name='signal_type',
            field=models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE candidate'), ('gift', 'In-call gift'), ('chat', 'Live In-Call Chat'), ('follow', 'Host Follow Event'), ('face_verified', 'Face Verified'), ('privacy_blur_engaged', 'Privacy Blur Engaged'), ('privacy_blur_lifted', 'Privacy Blur Lifted'), ('feeds_unlocked', 'Feeds Unlocked')], max_length=32),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='product',
            field=models.CharField(choices=[('DATING', 'Dating Premium'), ('HOOKUP', 'Hookup Premium'), ('SEX_CALL', 'Sex Call Premium'), ('COINS', 'Coin Pack'), ('HOOKUP_MATCH', 'Hookup Match Connection Fee')], default='DATING', max_length=20),
        ),
        migrations.CreateModel(
            name='HookupMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted - Awaiting Payment'), ('unlocked', 'Unlocked / Active Chat'), ('expired', 'Expired (24h Elapsed)'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('initiator_paid', models.BooleanField(default=False)),
                ('target_paid', models.BooleanField(default=False)),
                ('connection_fee', models.PositiveIntegerField(default=1500, help_text='Dual-fiat connection fee in NGN per participant (₦1,500)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_hookups', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_hookups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HookupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dating.hookupmatch')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hookup_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='hookupmatch',
            index=models.Index(fields=['initiator', 'status'], name='dating_hook_initiat_be05bd_idx'),
        ),
        migrations.AddIndex(
            model_name='hookupmatch',
            index=models.Index(fields=['target', 'status'], name='dating_hook_target__fdc680_idx'),
        ),
        migrations.AddIndex(
            model_name='hookupmessage',
            index=models.Index(fields=['match', 'created_at'], name='dating_hook_match_i_2eaa9e_idx'),
        ),
    ]
