# Generated by Django 6.0.1 on 2026-10-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0029_profile_off_platform_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_user_coins',
            field=models.PositiveIntegerField(default=100, help_text='Default coin balance for new user wallets'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hookup_connection_fee',
            field=models.PositiveIntegerField(default=1500, help_text='Connection fee in NGN per participant for Hookup Matches'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode to display maintenance page to non-admins'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='maintenance_message',
            field=models.TextField(default='We are currently undergoing maintenance. Please check back later.', help_text='Message displayed when maintenance mode is active'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='min_coins_for_video_call',
            field=models.PositiveIntegerField(default=20, help_text='Minimum coins required in wallet to initiate a video call'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy_url',
            field=models.URLField(blank=True, help_text='URL to Privacy Policy'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Contact email for support', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='support_whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number for support', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms_of_service_url',
            field=models.URLField(blank=True, help_text='URL to Terms of Service'),
        ),
    ]
