# Generated by Django 6.0.1 on 2026-10-08 00:08

import dating.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0030_siteconfiguration_default_user_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinwallet',
            name='coin_balance',
            field=models.PositiveIntegerField(default=dating.models.get_default_wallet_coins, help_text='Total spendable coin balance'),
        ),
    ]
