# Generated by Django 6.0.1 on 2026-10-09 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0033_profile_incognito_mode_profileview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='mode',
            field=models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SEX_CALL', 'Sex Call')], default='DATING', max_length=12),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_profile_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mode_switch_fee',
            field=models.PositiveIntegerField(default=200, help_text='Amount in Naira to charge when switching profile modes'),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='dating.profile'),
        ),
        migrations.CreateModel(
            name='ProfileStateBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('DATING', 'Dating'), ('HOOKUP', 'Hookup'), ('SEX_CALL', 'Sex Call')], max_length=12)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('first_date_idea', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('tags', models.ManyToManyField(blank=True, to='dating.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mode')},
            },
        ),
    ]
